services:
  repost-bot:
    build: .
    container_name: repost-bot
    restart: unless-stopped
    env_file:
      - .env

    volumes:
      - /home/shareFolder/rePost/downloads:/app/downloads
      - /home/shareFolder/rePost:/app/secrets

    environment:
      - YOUTUBE_CLIENT_SECRETS_PATH=/app/secrets/credentials.json
      - YOUTUBE_TOKEN_PATH=/app/secrets/token.json
      - INSTAGRAM_SESSION_PATH=/app/secrets/instagram_session.json
      - DOWNLOAD_DIR=/app/downloads
      - YTDLP_COOKIES_PATH=/app/secrets/youtube_cookies.txt
